name: Test CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment: DEV

    strategy:
      matrix:
        node: [14.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
