name: TEST CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    environment: TEST

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn test
